version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./config:/etc/nginx/conf.d:ro
      - ./certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - Web
    restart: always

networks:
  Web:
    name: Web